DROP TABLE IF EXISTS nxsidx_data_ingest.transaction_data_incoming;
CREATE TABLE nxsidx_data_ingest.transaction_data_incoming
(
    FILER_ID               int       NOT NULL,
    FILER_PREVIOUS_ID      varchar(10) default '',
    CAND_COMM_NAME         varchar(100) default '',
    ELECTION_YEAR          int        NOT NULL,
    ELECTION_TYPE          varchar(100) default '',
    COUNTY_DESC            varchar(255) default '',
    FILING_ABBREV          varchar(1) default '',
    FILING_DESC            varchar(80) default '',
    R_AMEND                varchar(1) default '',
    FILING_CAT_DESC        varchar(80) default '',
    FILING_SCHED_ABBREV    varchar(5) default '',
    FILING_SCHED_DESC      varchar(80) default '',
    LOAN_LIB_NUMBER        varchar(100) default '',
    TRANS_NUMBER           varchar(100) default '',
    TRANS_MAPPING          varchar(100) default '',
    SCHED_DATE             varchar(10) default '',
    ORG_DATE               varchar(10) default '',
    CNTRBR_TYPE_DESC       varchar(80) default '',
    CNTRBN_TYPE_DESC       varchar(80) default '',
    TRANSFER_TYPE_DESC     varchar(199) default '',
    RECEIPT_TYPE_DESC      varchar(80) default '',
    RECEIPT_CODE_DESC      varchar(80) default '',
    PURPOSE_CODE_DESC      varchar(80) default '',
    R_SUBCONTRACTOR        varchar(1) default '',
    FLNG_ENT_NAME          varchar(255) default '',
    FLNG_ENT_FIRST_NAME    varchar(100) default '',
    FLNG_ENT_MIDDLE_NAME   varchar(100) default '',
    FLNG_ENT_LAST_NAME     varchar(100) default '',
    FLNG_ENT_ADD1          varchar(100) default '',
    FLNG_ENT_CITY          varchar(100) default '',
    FLNG_ENT_STATE         varchar(30) default '',
    FLNG_ENT_ZIP           varchar(20) default '',
    FLNG_ENT_COUNTRY       varchar(20) default '',
    PAYMENT_TYPE_DESC      varchar(80) default '',
    PAY_NUMBER             varchar(30) default '',
    OWED_AMT               varchar(8) default '',
    ORG_AMT                varchar(12) default '',
    LOAN_OTHER_DESC        varchar(80) default '',
    TRANS_EXPLNTN          varchar(255) default '',
    R_ITEMIZED             varchar(1) default '',
    R_LIABILITY            varchar(1) default '',
    ELECTION_YEAR_R        varchar(4) default '',
    OFFICE_DESC            varchar(100) default '',
    DISTRICT               varchar(40) default '',
    DIST_OFF_CAND_BAL_PROP varchar(500) default '',
    TRIMM_CONTROL          varchar(5)   NULL,
    ROW_HASH               varchar(255) NULL
);

LOAD DATA INFILE '/mnt/volume_nyc3_01/var/lib/mysql-files/webapp/import_ny/cf_disclosure_report.csv'
INTO TABLE nxsidx_data_ingest.transaction_data_incoming 
fields TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\b' LINES TERMINATED BY '\n' IGNORE 1 LINES 
(filer_id,
filer_previous_id,
cand_comm_name,
election_year,
election_type,
county_desc,
filing_abbrev,
filing_desc,
r_amend,
filing_cat_desc,
filing_sched_abbrev,
filing_sched_desc,
loan_lib_number,
trans_number,
trans_mapping,
sched_date,
org_date,
cntrbr_type_desc,
cntrbn_type_desc,
transfer_type_desc,
receipt_type_desc,
receipt_code_desc,
purpose_code_desc,
r_subcontractor,
flng_ent_name,
flng_ent_first_name,
flng_ent_middle_name,
flng_ent_last_name,
flng_ent_add1,
flng_ent_city,
flng_ent_state,
flng_ent_zip,
flng_ent_country,
payment_type_desc,
pay_number,
owed_amt,
org_amt,
loan_other_desc,
trans_explntn,
r_itemized,
r_liability,
election_year_r,
office_desc,
district,
dist_off_cand_bal_prop,
@var) SET trimm_control = trim(TRAILING '\r' FROM @var), filer_id = upper(filer_id), filer_previous_id = upper(filer_previous_id), cand_comm_name = upper(cand_comm_name), election_year = upper(election_year), election_type = upper(election_type), county_desc = upper(county_desc), filing_abbrev = upper(filing_abbrev), filing_desc = upper(filing_desc), r_amend = upper(r_amend), filing_cat_desc = upper(filing_cat_desc), filing_sched_abbrev = upper(filing_sched_abbrev), filing_sched_desc = upper(filing_sched_desc), loan_lib_number = upper(loan_lib_number), trans_number = upper(trans_number), trans_mapping = upper(trans_mapping), sched_date = upper(sched_date), org_date = upper(org_date), cntrbr_type_desc = upper(cntrbr_type_desc), cntrbn_type_desc = upper(cntrbn_type_desc), transfer_type_desc = upper(transfer_type_desc), receipt_type_desc = upper(receipt_type_desc), receipt_code_desc = upper(receipt_code_desc), purpose_code_desc = upper(purpose_code_desc), r_subcontractor = upper(r_subcontractor), flng_ent_name = upper(flng_ent_name), flng_ent_first_name = upper(flng_ent_first_name), flng_ent_middle_name = upper(flng_ent_middle_name), flng_ent_last_name = upper(flng_ent_last_name), flng_ent_add1 = upper(flng_ent_add1), flng_ent_city = upper(flng_ent_city), flng_ent_state = upper(flng_ent_state), flng_ent_zip = upper(flng_ent_zip), flng_ent_country = upper(flng_ent_country), payment_type_desc = upper(payment_type_desc), pay_number = upper(pay_number), owed_amt = upper(owed_amt), org_amt = upper(org_amt), loan_other_desc = upper(loan_other_desc), trans_explntn = upper(trans_explntn), r_itemized = upper(r_itemized), r_liability = upper(r_liability), election_year_r = upper(election_year_r), office_desc = upper(office_desc), district = upper(district), dist_off_cand_bal_prop = upper(dist_off_cand_bal_prop);

UPDATE nxsidx_data_ingest.transaction_data_incoming
SET ROW_HASH = (SHA1(
        CONCAT_WS(FILER_ID, FILER_PREVIOUS_ID, CAND_COMM_NAME, ELECTION_YEAR, ELECTION_TYPE, COUNTY_DESC, FILING_ABBREV,
                  FILING_DESC, R_AMEND, FILING_CAT_DESC, FILING_SCHED_ABBREV, FILING_SCHED_DESC, LOAN_LIB_NUMBER,
                  TRANS_NUMBER, TRANS_MAPPING, SCHED_DATE, ORG_DATE, CNTRBR_TYPE_DESC, CNTRBN_TYPE_DESC,
                  TRANSFER_TYPE_DESC, RECEIPT_TYPE_DESC, RECEIPT_CODE_DESC, PURPOSE_CODE_DESC, R_SUBCONTRACTOR,
                  FLNG_ENT_NAME, FLNG_ENT_FIRST_NAME, FLNG_ENT_MIDDLE_NAME, FLNG_ENT_LAST_NAME, FLNG_ENT_ADD1,
                  FLNG_ENT_CITY, FLNG_ENT_STATE, FLNG_ENT_ZIP, FLNG_ENT_COUNTRY, PAYMENT_TYPE_DESC, PAY_NUMBER,
                  OWED_AMT, ORG_AMT, LOAN_OTHER_DESC, TRANS_EXPLNTN, R_ITEMIZED, R_LIABILITY, ELECTION_YEAR_R,
                  OFFICE_DESC, DISTRICT, DIST_OFF_CAND_BAL_PROP)))
WHERE 1 = 1;
CREATE INDEX idx_dev_populate_initial_row_hash ON nxsidx_data_ingest.transaction_data_incoming (ROW_HASH);
