
GRANT SELECT ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT INSERT ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT UPDATE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT DELETE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT CREATE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT DROP ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT RELOAD ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT PROCESS ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT REFERENCES ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT INDEX ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT ALTER ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT SHOW DATABASES ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT CREATE TEMPORARY TABLES ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT LOCK TABLES ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT EXECUTE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT REPLICATION SLAVE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT REPLICATION CLIENT ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT CREATE VIEW ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT SHOW VIEW ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT CREATE ROUTINE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT ALTER ROUTINE ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT CREATE USER ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT EVENT ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;
GRANT TRIGGER ON *.* TO 'nxs_admin'@'%' WITH GRANT OPTION;


GRANT SELECT ON *.* TO 'nxs_app'@'%' WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON dcnxs_app.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON dcnxs_ny.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON dcnxs_ugc.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON nxsidx_app.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON nxsidx_ny.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON nxsidx_ugc.* TO 'nxs_app'@'%';
GRANT INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON nxsidx_user_lists.* TO 'nxs_app'@'%';
GRANT CREATE, DROP, INDEX, ALTER, CREATE VIEW, CREATE ROUTINE, ALTER ROUTINE ON dcnxs_ugc.* TO 'nxs_app'@'%';
GRANT CREATE, DROP, INDEX, ALTER, CREATE VIEW, CREATE ROUTINE, ALTER ROUTINE ON nxsidx_ugc.* TO 'nxs_app'@'%';

